spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: elena
    password: geheimwasanderes
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
      platform: postgresql
      table-name: spring_session

server:
  servlet:
    session:
      timeout: 7d
      cookie:
        max-age: 7d

bucket4j:
  enabled: false
  filters:
    - name: rate-limit-filter
      url: /api/.*
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes