spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: elena
    password: geheimwasanderes
  jpa:
    hibernate:
      ddl-auto: update
bucket4j:
  enabled: true
  filters:
    - name: rate-limit-filter
      url: /api/.* # ⏱️ Schützt alle Pfade, die mit /api/ beginnen
      rate-limits:
        - bandwidths:
            - capacity: 60       # Maximal 60 Anfragen
              time: 1
              unit: minutes